name: Example Workflow Using Action.Test with env protection

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main
  merge_group:

jobs:
  get-env-permission:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    environment: env1
    steps:
      - run: echo "hi!!!"
  create-empty-commit:
    if: ${{ github.actor == 'dependabot[bot]' }}
    needs: get-env-permission
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Empty Commit
        run: >
          git checkout ${{ github.head_ref }} --; &&
          git -c user.name="github-actions[bot]" -c user.email="41898282+github-actions[bot]@users.noreply.github.com" 
          commit --allow-empty -m "Unlock secrets for dependabot" 
          --author="${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>" && 
          git push origin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run-action-test-2:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Kojoru's Action.Test
        uses: kojoru/Action.Test@v1
        with:
          # Specify inputs for the action, if any
          secret: ${{ secrets.SECRET }}
