name: Example Workflow Using Action.Test with env protection

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main
  merge_group:

jobs:
  get-env-permission:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    environment: env1
    steps:
      - run: echo "hi!!!"
  run-action-test-2:
    if: ${{ always() }}
    needs: get-env-permission
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Kojoru's Action.Test
        uses: kojoru/Action.Test@v1
        with:
          # Specify inputs for the action, if any
          secret: ${{ secrets.SECRET }}
